### ISSUE TITLE
Name not in package.json

### ISSUE THREAD

**Issue by balthazar** [meriadec/oooooo#1]
I think you are missing the name in the package.json, otherwise it can't publish to npm
pls fix!

**Comment by meriadec** [comment]
Oh ! Yes indeed ! Can you provide PR for it and eventually publish to npm? Thanks a lot

**Comment by meriadec** [comment]
still waiting...

**Comment by meriadec** [comment]
up (cc @balthazar )

**Comment by balthazar** [comment]
sory but i dont really now oh to do that, so youwill hav to do ite yourselve I guesse? as a leadev beste cripto wallait it should be quite ez zo no?
